Like.find_or_create_by(tweet_id: 1, user_id: 2)
Like.find_or_create_by(tweet_id: 1, user_id: 4)
Like.find_or_create_by(tweet_id: 1, user_id: 6)
Like.find_or_create_by(tweet_id: 1, user_id: 8)

Like.find_or_create_by(tweet_id: 2, user_id: 3)
Like.find_or_create_by(tweet_id: 5, user_id: 6)
Like.find_or_create_by(tweet_id: 1, user_id: 9)
Like.find_or_create_by(tweet_id: 9, user_id: 10)

Like.find_or_create_by(tweet_id: 3, user_id: 2)
Like.find_or_create_by(tweet_id: 4, user_id: 8)
Like.find_or_create_by(tweet_id: 3, user_id: 10)
Like.find_or_create_by(tweet_id: 8, user_id: 1)

Like.find_or_create_by(tweet_id: 7, user_id: 7)
Like.find_or_create_by(tweet_id: 13, user_id: 9)
Like.find_or_create_by(tweet_id: 6, user_id: 2)
Like.find_or_create_by(tweet_id: 7, user_id: 10)

Like.find_or_create_by(tweet_id: 5, user_id: 7)
Like.find_or_create_by(tweet_id: 6, user_id: 9)
Like.find_or_create_by(tweet_id: 11, user_id: 2)
Like.find_or_create_by(tweet_id: 10, user_id: 10)
Like.find_or_create_by(tweet_id: 13, user_id: 1)
